source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby <%= "'#{RUBY_VERSION}'" -%>

gem 'activerecord', '~> 5.0'
gem 'i18n', '~> 0.8'
gem 'pg', '~> 0.20'
gem 'puma', '~> 3.8'
gem 'rack', '~> 2.0'
gem 'rake', '~> 12.0'
gem 'telegram-bot-ruby', '~> 0.7'
